<?php

namespace App\FinanceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository {

    public function findAllOrderedByName() {

        return $this->getEntityManager()
                ->createQuery('SELECT p.name, p.price FROM AppFinanceBundle:Product p WHERE p.price < :price ORDER BY p.name ASC')
                ->setParameter('price', '25')
                ->getResult();
    }

}
